### ISSUE TITLE
Tag releases

### ISSUE THREAD

**Issue by legendofmiracles** [yskoht/keymapviz#59]
Hey! Awesome tool, it would be great if you could tag your releases (just normal git tags, no github releases needed) so that I can more easily package it in [nixpkgs](https://github.com/nixos/nixpkgs) 

Cheers

**Comment by yskoht** [comment]
@legendofmiracles 

Thanks for the nice suggestion!

I've tagged the past releases. And I'll make sure to tag future releases as well.

**Comment by legendofmiracles** [comment]
Thank you! 
I opened a PR here:

https://github.com/NixOS/nixpkgs/pull/145279
