### ISSUE TITLE
Any plans to make it compatible with other keyboards ?

### ISSUE THREAD

**Issue by powerlemming** [yskoht/keymapviz#9]

**Comment by yskoht** [comment]
@powerlemming 

If you request a keyboard you want to use, I'll add it. Or, you can even add it by yourself. Please look at https://github.com/yskoht/keymapviz/pull/3 .

**Comment by yskoht** [comment]
I welcome your contribution! Please send me any pull request :)

**Comment by powerlemming** [comment]
Could you give me guidelines as to what exactly I must add/include/change ?

**Comment by yskoht** [comment]
@powerlemming 

https://github.com/yskoht/keymapviz/blob/master/CONTRIBUTING.md
